### ISSUE TITLE
Refactor parse.server.ts to a class

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#112]
repo and truckignore parameters are being passed around just to keep them in scope. A class could fix this problem

**Comment by joglr** [comment]
What about having a config module that exports a `setConfig()` and `getConfig()` methods, with a global state? This module could then be mocked in tests. I don't like having a giant class with everything, but I don't know if that's just my opinion.

**Comment by joglr** [comment]
We have made a Git singleton ¯\\_(ツ)_/¯
