### ISSUE TITLE
Implement Dominant Authors metric based on git-blame

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#234]
In case Thomas finishes earlier than expected with the multi-branch analysis... I think this would be awesome to have :)

Surely, I'm saying Thomas because he seemed more dedicated to the parser, but I might be wrong here!

Also, if this is a duplication, then feel free to close it.

**Comment by joglr** [comment]
> In case Thomas finishes earlier than expected with the multi-branch analysis... I think this would be awesome to have :)
> 
> Surely, I'm saying Thomas because he seemed more dedicated to the parser, but I might be wrong here!
> 
> Also, if this is a duplication, then feel free to close it.

If only a tool existed for getting the information of who has worked most on a part of the code 😅

**Comment by mircealungu** [comment]
Turns out that I had confused @hojelse  and @tjomson already since the writing of this issue :) Sorry folks. Won't happen again!

**Comment by hojelse** [comment]
No worries!

**Comment by tjomson** [comment]
I wouldn't mind taking credit for the breadth first search. Kristoffer did an awesome job on that one 😁 🚀
