### ISSUE TITLE
investigate difficulty of adding controls for history parameters

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#239]
folks,

one thing that i'd like to discuss next time is: would it be hard to add controls for history parameters?

e.g. for git blame we could add the version on which to run the blame
for most active files we could add the time interval on which to compute the activity

m.

**Comment by tjomson** [comment]
Cool idea. This will probably require re-parsing when the version to run git blame with changes.
I wonder if we could have it not require re-parsing, by having some data structure that we can apply time-ranges to.

**Comment by tjomson** [comment]
https://www.git-scm.com/docs/git-blame#_specifying_ranges

**Comment by joglr** [comment]
We have implemented blame analyzation, but the feature is hidden due to it being unclear what it changes. Being able to select the blame commit might make it more useful.
