### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by hojelse** [git-truck/git-truck#284]
- [x] #326 
- [x] #289
- [x] #332
- [x] #287 
- [x] #290 
- [x] #288
- [x] Publish to NPM
- [x] Verify that `npx git-truck` works as expected
- [x] Verify that `npm i -g git-truck` works as expected
- [x] Unpublish broken versions (or deprecate)

**Comment by hojelse** [comment]
Transform bash scripts to some node server

**Comment by tjomson** [comment]
In most cases works with npx. Failing cases will be investigated when they are found
