### ISSUE TITLE
Setup project as an NPM package

### ISSUE THREAD

**Issue by hojelse** [git-truck/git-truck#288]
In `package.json`, these fields should be updated in order to run the tool.

- [x] Change `name` to `git-truck`
- [x] Change `private` to false
- [x] Add `description`
- [x] Add version
- [x] Set license
- [x] Use express remix deployment
- [x] Set "bin" to express entry point

**Comment by joglr** [comment]
To use an npm package as a cli, you need to specify `bin` in package.json.

When you `npm install` the package globally or `npx` the package, the package is automatically added to path by npm.
For example, for me, npm adds these executables:
![image](https://user-images.githubusercontent.com/1959615/158396449-5b4f08a9-a22e-40f2-9131-14ac0ef3eb0d.png)
Which I now can use from any folder I wish.

**Comment by joglr** [comment]
https://www.monkwhocode.com/2020/04/node-jsunderstanding-bin-in-packagejson.html?m=1
