### ISSUE TITLE
it would be nice to be able to chance the color for a given user

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#300]
one funny thing is that it seems that for the authors at least, there are many similar colors. in the figure below we have multiple similar blues and multiple similar greens. 

![image](https://user-images.githubusercontent.com/464519/157463656-ec55a6b9-1661-4c65-bc95-94250a795dad.png)

it would be awesome if I could click on the color dot near Beatrice and choose a different color. 

incidentally this could also work as a temporary solution to the same-author-multiple-names problem: i could simply select the same color for the various aliases.

also, some possible solutions for distinct colors seem to be discussed here: https://stackoverflow.com/questions/10014271/generate-random-color-distinguishable-to-humans

i think if we go with the observation that we don't want to have conflicts with the red highlight then we can simply remove the colors that have hue that's close to red?

**Comment by joglr** [comment]
This was also mentioned during a user evaluation session today

**Comment by joglr** [comment]
This has been partially addressed by #686 

It is possible to reroll the random colors.
