### ISSUE TITLE
Should the title of the dropdown be "Color"?

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#301]
It's true that in the dropdown we have metrics. 
However, we map them on the **color**.
Thus I wonder whether that wouldn't be a more intuitive dropdown title.

![image](https://user-images.githubusercontent.com/464519/157465132-e3a0a461-80ce-4531-b42f-32d6ac9c00cf.png)

**Comment by joglr** [comment]
Duplicated by #542
