### ISSUE TITLE
File names that include a space, break a few things

### ISSUE THREAD

**Issue by emiljapelt** [git-truck/git-truck#341]
- The displayed file name is only the first word
- Color lookups seem to fail

**Comment by tjomson** [comment]
This file is called *bruh moment xd.txt*
It is always red, but it's dot-color changed depending on the metric, always being the default color

![billede](https://user-images.githubusercontent.com/23435481/158553347-9902ff25-f604-4c36-85a4-1d4f7ce2bfcb.png)
