### ISSUE TITLE
Special characters are shown as codes

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#343]
cat-file and diff can't handle special characters

![billede](https://user-images.githubusercontent.com/23435481/158570703-178c1f5a-d586-4ced-90f9-d1f1659fcbd1.png)

fx. å, ø, β

**Comment by joglr** [comment]
Acoordint to [this](https://stackoverflow.com/questions/10687589/git-how-to-specify-file-names-containing-octal-notation-on-the-command-line), git uses [octal notation](https://mathiasbynens.be/notes/javascript-escapes#octal) to represent non-ASCII characters.

**Comment by joglr** [comment]
I don't understand though, why JavaScript finds it difficult to parse:
![image](https://user-images.githubusercontent.com/1959615/158870023-edcac289-c9c4-4e73-8dcc-2bb25528e519.png)

**Comment by joglr** [comment]
> 

This solves the issue for me:
![image](https://user-images.githubusercontent.com/1959615/158870908-7d91514e-fc1e-498b-9996-b265d4a1ab11.png)

However, changing git user settings is maybe a bit user hostile.
