### ISSUE TITLE
Fix npx 404 for some systems (Thomas' funky problems)

### ISSUE THREAD

**Issue by hojelse** [git-truck/git-truck#368]

**Comment by tjomson** [comment]
![billede](https://user-images.githubusercontent.com/23435481/159224345-419120ed-52bc-4f10-b775-1726a306571f.png)

**Comment by joglr** [comment]
Can you try reproduce with `npx git-truck@0.8.14-0` ? If you can't reproduce, then #506 might have fixed it.

**Comment by tjomson** [comment]
It still says "express server listening", so it is just funky. Closing this issue, because most likely is caused by some old version i have locally
