### ISSUE TITLE
noCommits is not always correct

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#374]
Running `git blame --show-stats` on details OptionsContext.ts gives
![billede](https://user-images.githubusercontent.com/23435481/159159005-c43a8964-2fe1-409e-ac4a-570234401333.png)

but the UI says 9 commits.
Likewise parse.ts should have 42, but UI says 41

**Comment by joglr** [comment]
Maybe related to #365

**Comment by tjomson** [comment]
Using `git log` this is not an issue. Commits with no changes are skipped, but this should be fine
