### ISSUE TITLE
Argument to not parse on reload

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#377]
Such that you can `npm run dev` and make changes to UI without rerunning the parser

Maybe `--no-reload`

**Comment by tjomson** [comment]
Can be coupled with a UI button to reparse

**Comment by joglr** [comment]
Relevant to #336 

Maybe default should cache and then we could have a --no-cache flag?

**Comment by tjomson** [comment]
These solutions seem smart, but i think the cleanest solution would be to just have a button to trigger the parser

**Comment by joglr** [comment]
A quick solution for the catching could just be checking if the json file already exists. If it does, just serve that. Combined with your idea with the reparse button.

**Comment by joglr** [comment]
Closing, since this kindof is implemented by the caching strategy. Does it still make sense to have the CLI flag?

**Comment by tjomson** [comment]
> @tjomson Closing, since this kindof is implemented by the caching strategy. Does it still make sense to have the CLI flag?

Yep, dats fine
