### ISSUE TITLE
Refactor metrics to be expandable

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#441]
To enable #234 and may also make the code cleaner

**Comment by tjomson** [comment]
can also enable #300

**Comment by joglr** [comment]
There are also some other issues, for example that we don't have a way for specifying whether a legend label should be formatted as a date, see [here](https://github.com/git-truck/git-truck/pull/439#pullrequestreview-924530141).

**Comment by joglr** [comment]
I also thought about whether the metrics should be scoped to the selected folder? The min/max i mean.

**Comment by hojelse** [comment]
Make GradLegendData and PointLegendData object oriented. The array returned by getMetricCalcs() looks like it wants to be classes that is instantiated, instead of array literals.

**Comment by joglr** [comment]
@emiljapelt Is this implemented?

**Comment by joglr** [comment]
I talked to @emiljapelt who says this is partially implemented, so I will close this issue
