### ISSUE TITLE
activity mapped on orange instead of red? 

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#444]
otherwise selection is a bit awkward? 

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/464519/160628373-385c5446-f2a3-4806-a431-d900f68ddd21.png">

**Comment by joglr** [comment]
Yes, the red is problematic. Generally we need to overhaul the colors in the application. The dominant author colors are not very distinguishable from each other.

**Comment by tjomson** [comment]
I think it is more a problem with the search giving red borders to search results. We need some indication that works on all colors of nodes. This could for example be an animation on the border with multiple colors or something like that

**Comment by tjomson** [comment]
Closed in #568
