### ISSUE TITLE
very slow animations

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#451]
folks,

the animations are very very laggy today.
is there a reason for that?
is my machine tired?

m.

**Comment by joglr** [comment]
We compared with and without animations and with and without folder names. They are both very resource intensive, but the biggest offender seemed to be the folder names.

**Comment by tjomson** [comment]
I think it is also a problem that everything is rendered, even if it is so small that you can't even see the individual files. I think we need a cutoff so that we only render files that can actually be seen. I added this issue #459

**Comment by tjomson** [comment]
Version 0.7.6 is now on npm. It is a bit more performant

**Comment by mircealungu** [comment]
Zooming in animations are still quite slow…

M.
