### ISSUE TITLE
Searching updates a lot of UI

### ISSUE THREAD

**Issue by joglr** [git-truck/git-truck#491]
![image](https://user-images.githubusercontent.com/1959615/161746267-b46649f8-0693-42fe-848c-9ff83b3891f8.png)

**Comment by joglr** [comment]
This was captured using React Developer Tools

**Comment by joglr** [comment]
The same goes for the "Enable animations" checkbox

**Comment by joglr** [comment]
@tjomson @hojelse @emiljapelt 
Instead of having so many contexts, we could use [zustand](https://github.com/pmndrs/zustand).

Zustand has a very nice API for only depending on the state that the component needs:
```typescript
import create from 'zustand'

const useStore = create(set => ({
  deers: 0,
  bears: 0,
  increaseBearPopulation: () => set(state => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
  increaseDeerPopulation: () => set(state => ({ deers: state.deers + 1 }))
}))
```

Say we only need to depend on the `deers` part of the store, we can do so by calling the `useStore` hook and giving it a function that specify what we need:

```typescript
function INeedDeer() {
  const deers = useStore(state => state.deers)

  // render something cool deer stuff
}
```

This way, the INeedDeer component only rerenders if `deers` change.

You can have multiple selectors:


```typescript
function INeedDeer() {
  const deers = useStore(state => state.deers)
  const bears = useStore(state => state.bears)

  // render something cool deer stuff
}
```

Zustand is maintained by the [pmndrs](https://github.com/pmndrs) collective that is also responsible for react-spring, react-three-fiber, and other cool projects.

Zustand is one of the most popular react state management libraries.

**Comment by tjomson** [comment]
@joglr is this still relevant?

**Comment by joglr** [comment]
I think so

**Comment by joglr** [comment]
No longer an issue with React 18.
