### ISSUE TITLE
Show commit history for a single file

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#549]

**Comment by dawidwoz** [comment]
![image](https://user-images.githubusercontent.com/52498300/198700467-81c5a66a-75c3-4b73-839c-2a8f09c0e7d9.png)
I've been thinking about how you would like to implement it in terms of UI and functionality. My first thought is that it should look like the author's view with the date of commit next to it.

**Comment by mircealungu** [comment]
Something like this I have in mind: 

![image](https://user-images.githubusercontent.com/464519/198713686-bf9a9573-186b-47a3-9989-4f33251755a6.png)

when you select an element in the main view, you get to see 
the comments in a detail view.

you can start with files, and then later make it work also for 
folders: which is what I have tried to highlight in the mockup above. 

see what i mean?
