### ISSUE TITLE
default view

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#570]
Folks,

Reading the report of a student who tried to use both GT and Wattenberger's online repo visualization:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/464519/170197177-ec7ae4f3-68c3-4a7c-858c-db26e206a9c4.png">

It made me wonder: why did the student think the two were "strikingly similar"? And I think that's because we start with the same file-type view as Amelia. But we're named git-truck; we are supposed to be inspired by the truck factor... So why don't we start with something more ... truck-factor-y? The author dominance views maybe?

**Comment by joglr** [comment]
Isn't it to onboard the user with a more simple view in the beginning? However, this is just an assumption I have, that we should test!

**Comment by mircealungu** [comment]
yes; there's the argument of a simple view; also, a simple view helps with filtering out big files maybe?

**Comment by joglr** [comment]
Yes.. we must test our assumptions

**Comment by joglr** [comment]
We have decided to keep the file type as default and remember the last selected view. We have also sorted the views by popularity in the survey.
