### ISSUE TITLE
Improve color scale of the "last changed" view

### ISSUE THREAD

**Issue by jeppe-style** [git-truck/git-truck#572]
With the current colour scale it is very difficult to differentiate when a file was last changed. See screenshot below.

![image](https://user-images.githubusercontent.com/8646217/172411508-9e5d9b89-76b3-47a9-b4f9-6c2c0330894b.png)

**Comment by joglr** [comment]
Yeah, the last changed view is definetely problematic. We are working on finding better methods for this view. 

Amelia Wattenberger uses a pretty neat scale, that is skewed:
![image](https://user-images.githubusercontent.com/1959615/172934942-74c5b0d1-2118-4f76-a355-52c84f9e36df.png)

https://githubnext.com/projects/repo-visualization/

**Comment by jeppe-style** [comment]
nice! That could be a good idea to use a skewed scale since you mostly care about differentiating which files are stable and which are actively being worked on.

d3.js has some nice color scales. Probably you can skew them also:
https://github.com/d3/d3-scale-chromatic#sequential-single-hue
