### ISSUE TITLE
Combine "single author" with "number of commits"

### ISSUE THREAD

**Issue by jeppe-style** [git-truck/git-truck#573]
In order to have a better understanding of which files are more critical when considering the truck-factor it would be useful to combine the "single author" view with the "number of commits" (color saturation/intensity).

For example if a file has a single commit it is natural that there is a single author, whereas if a file has many commits it would be expected that they are done by multiple authors.

Maybe also do the same should be done for the "top contributor" view?

**Comment by joglr** [comment]
This is now possible by selecting size metric in the latest version. Such that, you can change the files to be sized by the amount of commits. Feel free to reopen the issue if you disagree.
