### ISSUE TITLE
Differentiate authors by color in "single author" visualization

### ISSUE THREAD

**Issue by jeppe-style** [git-truck/git-truck#574]
When looking at the "single author" visualization all files with a single author have the same color, however, they are probably not the same author. If the author of the single commit is shown (e.g., by differentiated colors) it would be possible to analyze the truck-factor=1 problem more in depth. This is similar to the "top contributor" visualization, however, having truck-factor=1 might indicate a more severe problem.

**Comment by joglr** [comment]
Related to #573
