### ISSUE TITLE
Error when trying with relatively large repository

### ISSUE THREAD

**Issue by enderyuksel** [git-truck/git-truck#576]
Trying git-truck in my work repo (20+ contributors, github settings/repositories claim it is 611MB, yet I suspect it is way larger), as you can see from the screenshots the tree hydration took almost an hour, and then after a similar amount of time and then failed with the error messages below.  FYI, the json file is 249MB.
![image (1)](https://user-images.githubusercontent.com/2356653/172783958-746d2821-b1b3-4f7b-a262-4a86c50c763c.png)
![image (2)](https://user-images.githubusercontent.com/2356653/172783975-5f41165f-b89a-410d-a818-0b421264d2c7.png)

I can suggest trying multithreading, for reducing the analysis time for the least. Also perhaps checking upfront if a repo size is too large to try, to avoid user waiting.

**Comment by enderyuksel** [comment]
I just did, thank you.

**Comment by tjomson** [comment]
There is a limit of 512 MB on the size of a string, this problem is probably due to that. This is only the second time that it has been a problem, but i guess we will have to make a solution for it :/
