### ISSUE TITLE
Recognize Jupyter Notebook file extensions

### ISSUE THREAD

**Issue by jeppe-style** [git-truck/git-truck#577]
Jupyter Notebooks (`.ipynb`) are a common filetype for student projects (specially data analysis), however, they are currently shown as `other` which makes it hard to identify them.

**Comment by joglr** [comment]
I just found this package: 
https://github.com/blakeembrey/language-map/
Which seems to have ipynb listed here:
https://github.com/blakeembrey/language-map/blob/main/languages.json
We could experiment with changing to using that package instead.
