### ISSUE TITLE
Change the mapping or Last Changed. Start from something that’s white and keep it very light for the first 1/3 of the history or so. Such that we can discriminate better the old files.

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#582]

**Comment by mircealungu** [comment]
Is this released? 

Because in GT 1.1.0 I still see this:

![Image](https://user-images.githubusercontent.com/464519/174943687-4ab14908-e799-4e57-8349-d755236ee202.png)

In fact, what would probably be even better here would be a different mapping, that is not necessarily linear. 

Maybe a discrete mapping with levels that would be logarithmic? 

1 week
2 weeks
1 month
2 months
4 months
1 year
2 years
4 years
8 years
> more than 8 years

So an algorithmic approach would be something like: 
- take the total interval (e.g. 4 years) 
- keep dividing it in two for ten times to get (4y, 2y, 1y, 6m, 3m, 6w, 3w, 10d, 5d, 2d) 
- for each of the intervals, have a distinct color of blue

I think that would generate much more meaningful visualizations. 

What do you think?

**Comment by joglr** [comment]
Duplicate:
https://github.com/git-truck/git-truck/issues/572

**Comment by mircealungu** [comment]
Last one is the best!

**Comment by mircealungu** [comment]
Ah, look how beautiful all the files in v1 folder are darker than the v2 folder :)
@emiljapelt - can I try this version somewhere? can you release it maybe?

**Comment by emiljapelt** [comment]
@mircealungu 
It is currently on branch '582/improving-last-changed', which also includes a first draft of a truck-factor view.

**Comment by mircealungu** [comment]
Thanks @emiljapelt .

Can you try to get an image of ArgoUML (https://github.com/argouml-tigris-org/argouml) ?

I can't seem to be able to get it running from code on my machine due to some style-components error? 
Anybody seen this before?

```
➜  git-truck git:(582/improving-last-changed) ✗ npm start

> git-truck@1.1.0 start
> cross-env NODE_ENV=production node ./build/index.js

/Users/gh/git-truck/build/index.js:128
      throw false ? new Error("An error occurred. See https://git.io/JUIaE#" + e2 + " for more information." + (n2.length > 0 ? " Args: " + n2.join(", ") : "")) : new Error(b.apply(void 0, [E[e2]].concat(n2)).trim());
      ^

Error: Cannot create styled-component for component: undefined.
    at _ (/Users/gh/git-truck/build/index.js:128:164)
    at e3 (/Users/gh/git-truck/build/index.js:656:18)
    at ke (/Users/gh/git-truck/build/index.js:665:8)
    at Object.<anonymous> (/Users/gh/git-truck/build/index.js:5132:56)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47


```

**Comment by emiljapelt** [comment]
That unfortunate, I have not seen such an error before. However, I was able to visualize argouml, here are the results:
![FileEx](https://user-images.githubusercontent.com/55390848/175761338-3cc4aafd-eb50-4b40-aaea-229798fae4d1.PNG)
![Commits](https://user-images.githubusercontent.com/55390848/175761339-debd65fb-504b-4935-af30-0790ddc4b6c3.PNG)
![LastChanged](https://user-images.githubusercontent.com/55390848/175761345-52a1aa17-d68d-4293-8f78-eedb200ea574.PNG)
![SingleAuthor](https://user-images.githubusercontent.com/55390848/175761349-9cffdf7a-425a-4a08-886c-29047616071b.PNG)
![TopCon](https://user-images.githubusercontent.com/55390848/175761354-717a8790-3025-4e15-98d4-b8e6ed95b76a.PNG)
![Truck](https://user-images.githubusercontent.com/55390848/175761358-5087f4f6-2392-4d93-b5a9-df662f9e458e.PNG)
