### ISSUE TITLE
riddle: can you spot the bug?

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#584]
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/464519/174689543-4f0dcf1b-de8c-4fd2-950a-aa6d188871a8.png">

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/464519/174689566-cd6a186f-feb1-41e3-bef0-ca1708dc3067.png">

**Comment by tjomson** [comment]
Colors are not consistent when changing branch? #513

**Comment by mircealungu** [comment]
you're both right. Unfortunately, circle positions are probably much harder to solve than colors

**Comment by joglr** [comment]
> you're both right. Unfortunately, circle positions are probably much harder to solve than colors

Yes. Wattenberger solved it by using D3 Physics

**Comment by joglr** [comment]
Duplicate of #547
