### ISSUE TITLE
Color Legend Near Author distribution

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#585]
Color Legend Near Author distribution would make my life easier :) 
Please describe your idea / problem below:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/464519/175290293-392abea1-0d84-4205-9f07-c9ee4b01ee4d.png">

**Comment by joglr** [comment]
@mircealungu I've made an attempt to implement this:

![image](https://user-images.githubusercontent.com/1959615/195990539-e0f34c26-65b6-4995-99fa-8a42d19fd8fe.png)

The following question however regards to whether this is confusing to display when the current view is not top contributor? Let me know your thoughts

I've published an experimental release with this implemented

git-truck@0.0.0-f2f1a88

Feel free to try it out :)

**Comment by mircealungu** [comment]
Thanks for trying out this @joglr !

Indeed, it is a bit confusing when the current view is not top contributor - It is not clear which colors are being mapped in the main view: 

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/464519/196030791-39351bcb-4a2b-4371-bb6e-d35f41dcba83.png">

If it's not "ugly" to only make it visible in the top-contributor view that would be an option. Otherwise, let's save tag this discussion with "decisiosn" or something so I don't come back with the same idea half a year later :)

**Comment by joglr** [comment]
I guess we could try to only show it in the top contributor view, as long as it is not confusing to the user. The question becomes whether the author distribution should even be visible when top contributor is selected? Maybe we could show something that is more relevant to the selected metric.
