### ISSUE TITLE
adapting the color scale after removing outlier

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#588]
looking at number of commits in sqlite, i see that the manifest file has 22K commits. 
so i filter it out. 
however, the range does not adjust.
shouldn't it? 

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/464519/190482833-0f5d5485-6777-48af-b993-8224eea2e129.png">

**Comment by joglr** [comment]
Yes, it definitely should. This could and should be tackled even before working on other issues relating the range.

**Comment by emiljapelt** [comment]
This is now implemented on branch 588/Dynamic-numberOfCommits-gradient. Please check it out :)

**Comment by joglr** [comment]
> oh shucks! how do i try it if it's not released?

I can make an experimental release you can test. 

FYI: There is also another upcoming release that improves global install time by a factor **28x** 🤯 and NPX with a factor of **3.5x**

**Comment by joglr** [comment]
@mircealungu I have released this experimental release that you can try out:
```
git-truck@0.0.0-3e8160c6
```
