### ISSUE TITLE
Use zlib instead of cat-file

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#60]
- read pack-files
- read trees

May give performance improvement?

**Comment by emiljapelt** [comment]
Info of packfile formats: https://git-scm.com/docs/pack-format/en

**Comment by emiljapelt** [comment]
pack-*.idx, are used for getting the required lookup data, to lookup a file in the corresponding pack-*.pack file

**Comment by tjomson** [comment]
This would be very difficult to do right. Our performance is good enough now, that we do not need to worry about this.
