### ISSUE TITLE
Interface crashing

### ISSUE THREAD

**Issue by stephanboersma** [git-truck/git-truck#619]
Hey,

Wanted to show your tool to my colleagues but the UI crashed when loading the page. The command used: `npx -y git-truck ./repo-name`
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/32750681/231970517-dea5cf81-91af-4d6e-b11f-a857b8234663.png">

The terminal is just looking for branch head:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/32750681/231970601-26e760ec-fc71-47ec-8614-8d790b3ae389.png">

When running `npx -y git-truck` in the git directory, the page loads but styles are missing and following error is found in the console.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/32750681/231970820-b4c0d5b5-1c59-4ca4-b18a-fea9f9d465e6.png">
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/32750681/231971028-b03b44b2-fb2e-43d5-a063-63c31e76507c.png">

**Comment by joglr** [comment]
Hello! Thank you for reporting this issue. Can you tell a bit about your setup (OS, node version, git-truck version, which repository you ran the tool with, etc.). The styling missing is a known issue, #617 that I am currently working on fixing.

**Comment by stephanboersma** [comment]
Sure thing.
<img width="220" alt="image" src="https://user-images.githubusercontent.com/32750681/233148301-e417ccc1-963d-4793-97b6-e4a332e552d9.png">

Node version 16.17.1
git-truck version 1.3.2

The repository is private so unfortunately I cannot share this with you. 

It is a monolith that contains:
- several npm packages that are bootstrapped using lerna
- A Frontend Client in a javascript framework
- A Backend in C#

**Comment by joglr** [comment]
Thank you for the context Stephan! And also thank you for your awesome work with react-bratus, it was an inspiration to this project! :)

**Comment by joglr** [comment]
Can you try with `git-truck@experimental`?

**Comment by joglr** [comment]
Oh, you should use --path instead of providing the path directly.

**Comment by joglr** [comment]
Thank you for trying it. I think I narrowed down the location of the issue. I will create a bugfix soon.

**Comment by joglr** [comment]
Can you provide me with the name of the branch currently checked out in the repository?

**Comment by stephanboersma** [comment]
Hi @joglr ,

It was checked out on the develop branch :-) Let me know if you need anything further.

**Comment by joglr** [comment]
Can you try with `git-truck@latest`?

**Comment by stephanboersma** [comment]
It works 🥳
