### ISSUE TITLE
crashing in Safari

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#622]
i open repo in safari;
try to change vis to number of commits
get this:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/464519/236063149-0fdd3d36-28ab-428d-98ba-662774aac617.png">

**Comment by joglr** [comment]
Anything in the console?

**Comment by mircealungu** [comment]
good question! this is a pic. let me know if you need text

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/464519/236191557-21dcde53-b4ab-400b-86e9-18aad5747a00.png">

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/464519/236191760-343a91da-2164-4dcd-b581-cfd39e38d497.png">

**Comment by joglr** [comment]
I have created a fix.

Can you reproduce it with with `npx -y git-truck@0.0.a7e15cd`?

**Comment by mircealungu** [comment]
➜  api git:(master) ✗ npx -y ***@***.*** 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ***@***.***
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mircea/.npm/_logs/2023-05-05T13_32_39_888Z-debug-0.log

**Comment by joglr** [comment]
I wrote the wrong version initially, so it might still be stale in the email. Can you try again with either `npx -y git-truck@0.0.0-a7e15cd` or `npx -y git-truck@experimental`

**Comment by rasmusroessum** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/35430583/236684742-d472219b-d656-4e87-bc27-b594519c07c9.png">
![image](https://user-images.githubusercontent.com/35430583/236684760-1b549951-9c2c-43af-9c01-956c9b68bed8.png)
![image](https://user-images.githubusercontent.com/35430583/236684775-4844b4ae-0ebe-44ec-ad3b-b8f19acf1b56.png)

**Comment by mircealungu** [comment]
sorry for the slow response time!
it works indeed!

￼

M.
