### ISSUE TITLE
[Regression] If the port 3000 is taken, the application fails to start

### ISSUE THREAD

**Issue by dawidwoz** [git-truck/git-truck#649]
Please describe your idea / problem below:
Currently, if port 3000 is taken, the application fails to start with the following error:
![image](https://github.com/git-truck/git-truck/assets/52498300/3c2ca912-436b-4778-af5c-ac0c26768615)

It used to move to another free port, e.g., 3001. Somehow between the version, it lost this capability.

**Comment by joglr** [comment]
This is a known problem. It is only an issue in local development, since this does not utilize our `cli.ts` file. I think the remix serve command might accept a port argument, e.g.

```
npm run dev -- --port 3001
```
