### ISSUE TITLE
Prune tree of small nodes before hierarchy is generated

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#690]
E.g. if size metric is commits, and the repo has a file with 10.000 commits, then a file with 3 commits will probably not be visible, so we can prune it before generating the hierarchy, improving performance.

Optionally, we could also make a slider for how agressive this pruning should be. E.g. remove files with commits less than 10% of the maximum

**Comment by joglr** [comment]
This is a very good idea, as generating the layout / hierarchy is a very expensive computation. It would be interesting to know the time complexity of the underlying algorithm.

**Comment by tjomson** [comment]
This idea is pointless.
For the linux-repo with 81k files, generating the hierarchy takes less than 400 ms in the worst case
