### ISSUE TITLE
Git Truck fails to start on Node versions < 18

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#710]
I'm failing to start the truck on MacOS Somona 
<img width="484" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/f5a887cc-db04-4f6b-886b-92aaf92bd5b4">

<img width="1201" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/fba74ff6-2ad3-442c-bdd7-09fbbcf3e7e5">

any idea what might be the problem?

**Comment by joglr** [comment]
Noticed this today as well. We updated to remix v2. It seems they dropped support for Node 16, supporting 18 and above. Which node version are you on? We should update the information in the README

**Comment by joglr** [comment]
We should probably also have bumpede the major version in this regard... 🤷🏼‍♂️ We could show a notice if an unsupported node version is used.

**Comment by joglr** [comment]
I can reproduce on Windows with Node 16.13.2
![image](https://github.com/git-truck/git-truck/assets/1959615/95191c58-6e76-493f-bfbe-3b31b6402d4d)

**Comment by joglr** [comment]
I have made a PR that bumps the engines field. This will display an error when trying to use Git Truck with an old Node version.

The error looks something like this:

```bash
npx -y git-truck@2.0.0 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'git-truck@2.0.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'git-truck@1.8.3',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
sh: 1: git-truck: not found
```

**Comment by mircealungu** [comment]
indeed. I'm on node 16.3

**Comment by joglr** [comment]
This is one approach, another would be "supporting" all Node versions and displaying a nicer message that tells the user to upgrade their Node version.

**Comment by mircealungu** [comment]
eheh - surely a nicer error message would be nicer :) 
but if it's too much work, then maybe better implement something else, e.g. the Frozen color scheme ;)

**Comment by mircealungu** [comment]
@joglr - also, don't forget about the Readme... 
<img width="632" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/621b99cd-1674-4315-92b3-79d44c96637e">

**Comment by joglr** [comment]
Thank you, I already forgot.

**Comment by joglr** [comment]
> eheh - surely a nicer error message would be nicer :) 
> but if it's too much work, then maybe better implement something else, e.g. the Frozen color scheme ;)

Good idea, the new error message clearly tells the user that their Node version is too old, so I think it works well. The Frozen Color scheme is really cool, we should get to that ASAP.
