### ISSUE TITLE
It should be possible to see commit details

### ISSUE THREAD

**Issue by dawidwoz** [git-truck/git-truck#724]
Please describe your idea / problem below:
Currently, there is no view for commit details including description, exact creation date, author and edited files. Let's add it.

**Comment by dawidwoz** [comment]
Really nice experience! Good job @tjomson @joglr! 👍 

![image](https://github.com/user-attachments/assets/075e7e0b-45d8-496e-913e-8f3472b378f7)

**Comment by joglr** [comment]
> Really nice experience! Good job @tjomson @joglr! 👍 
> 
> ![image](https://github.com/user-attachments/assets/075e7e0b-45d8-496e-913e-8f3472b378f7)
> 

Credit goes to @tjomson and his master thesis 😎
