### ISSUE TITLE
1.10 crashing on Safari?

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#736]
this is what I see:
<img width="767" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/6c755704-57cc-4a58-ba75-178c6a9e3e55">

and from the console: 
<img width="1018" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/355be3c6-c4ee-4da1-a4ff-78fc37009306">

**Comment by joglr** [comment]
v.1.10.1 released, should fix the problem.

**Comment by mircealungu** [comment]
this was quite a fast reaction time @joglr  :)

**Comment by joglr** [comment]
> this was quite a fast reaction time @joglr :)

As always 😅
