### ISSUE TITLE
Labels don't move when updating the time range

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#745]
tagging you @tjomson so you don't forget about it. and @joglr because you might have insight :)

<img width="1434" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/15ce1141-061a-42b6-af28-9f6342af72e5">

<img width="1498" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/b4299ae1-c28a-4060-9212-02d2b4f2443c">

extra info
- only on Chrome
- if i hide and show lables from the UI, it fixes it

<img width="361" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/02d88e88-517a-4635-9613-54705488e6c1">

**Comment by joglr** [comment]
Yes, it's very annoying, it is also repoted here: #681
