### ISSUE TITLE
Mercurial Support?

### ISSUE THREAD

**Issue by kovasap** [git-truck/git-truck#755]
Any plans to support mercurial with this tool?  It may be easier for me to make a converted git copy and the run the tool, but thought I'd ask here anyway.

**Comment by joglr** [comment]
Hi! It is not something we have heard any interest of before - are you aware of many developers that use Mercurial? It is not something we have planned to work on, unless there is a large demand for it, as you say, I would guess that it will be quite some work to make Git Truck work with Mercurial projects. Are you aware of any tools that can convert a Mercurial project to git?

**Comment by kovasap** [comment]
I think there are some tools to convert.  There are a decent amount of
mercurial users, but I wouldn't add support unless (1) it's easy, or (2)
this issue gets more traction.
