### ISSUE TITLE
Configuration for preferred Code Viewer? 

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#757]
On a Mac I get to install XCode if I want to see the contents of a file. This seems a bit annoying: 

<img width="1008" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/11b668ed-83cd-4fc0-9703-fa54b1b27f50">

**Comment by joglr** [comment]
This is configured in the system, and the library we use to open files use what is configured as the default in the system. I can see why this is annoying, but it would also be weird to begin assuming what programs the user should use, and configuring this in Git Truck as well seems a bit overkill imo. What do you think?

**Comment by mircealungu** [comment]
that's a good point. 
now i'm on a different machine and since i have VSCode on it, this one jumps always first to open... and it's fine.
