### ISSUE TITLE
git-truck@duck doesn't work

### ISSUE THREAD

**Issue by zndr27** [git-truck/git-truck#758]
Running "npx -y git-truck@duck" throws a bunch of warnings and is stuck in a loop without opening the app. Sometimes it closes with an error too.

When i just run "npx -y git-truck" everything works fine.

**Comment by joglr** [comment]
Thank you for flagging your issue! The beta build of git truck has some knows issues. Can you provide some more context?

- OS + version
- Architecture
- Node.js version

**Comment by joglr** [comment]
I will close this issue, feel free to comment if you have more information that can help us resolve your issue.
